export const ADD_INCOME = "ADD_INCOME"
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const GENERATE_TABLE = 'GENERATE_TABLE'
export const MANAGE_BALANCE = 'MANAGE_BALANCE'
export const ADD_OUTGOINGS = 'ADD_OUTGOINGS'
export const RESET_STATE = 'RESET_STATE'

export const INCOME_HISTORIC = 'INCOME_HISTORIC'
export const I_HISTORIC_QUERY = 'I_HISTORIC_QUERY'
export const GENERATE_REPORT_I = 'GENERATE_REPORT_I'
export const INCOME_HISTORIC_CONTENT = 'INCOME_HISTORIC_CONTENT'

export const OUTGOINGS_HISTORIC = 'OUTGOINGS_HISTORIC'
export const O_HISTORIC_QUERY = 'O_HISTORIC_QUERY'
export const GENERATE_REPORT_O = 'GENERATE_REPORT_O'
export const OUTGOINGS_HISTORIC_CONTENT = 'OUTGOINGS_HISTORIC_CONTENT'