export const ADD_INCOME = "ADD_INCOME"
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const GENERATE_TABLE = 'GENERATE_TABLE'
export const MANAGE_BALANCE = 'MANAGE_BALANCE'
export const ADD_OUTGOINGS = 'ADD_OUTGOINGS'
export const RESET_STATE = 'RESET_STATE'